services:
  orbix-ai:
    build: .
    container_name: orbix-ai-platform
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - orbix-network

  # Nginx para HTTPS y load balancing
  nginx:
    image: nginx:alpine
    container_name: orbix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - orbix-ai
    restart: unless-stopped
    networks:
      - orbix-network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: orbix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orbix-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  orbix-network:
    driver: bridge

volumes:
  logs:
    driver: local
  redis_data:
    driver: local
